nejibem_whattoeat_homepage:
    pattern:  /
    defaults: { _controller: NejibemWhattoeatBundle:Default:whattoeat }

nejibem_whattoeat_recipes:
    pattern:  /recipes
    defaults: { _controller: NejibemWhattoeatBundle:Default:recipes }
